services:
  app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    command: npm run start:prod
